version: '3.8'

services:
  cassandra-1:
    image: cassandra:4.1
    container_name: kinoprogramm-cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=KinoprogrammCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"   # CQL native transport port
      - "7000:7000"   # Inter-node cluster communication
      - "7001:7001"   # TLS inter-node cluster communication  
    networks:
      - kinoprogramm-netzwerk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-2:
    image: cassandra:4.1
    container_name: kinoprogramm-cassandra-2
    environment:
      - CASSANDRA_CLUSTER_NAME=KinoprogrammCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2 # Dieser Server ist in einem anderen Server-Schrank
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_SEEDS=cassandra-1  # This connects to the first node
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9043:9042"   # Different host port to avoid conflict
      - "7002:7000"   # Different host port
      - "7003:7001"   # Different host port
    depends_on:
      cassandra-1:
        condition: service_healthy
    networks:
      - kinoprogramm-netzwerk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: kinoprogramm-cassandra-web
    environment:
      - CASSANDRA_HOST_IPS=cassandra-1
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=
      - CASSANDRA_PASSWORD=
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "3000:8083" # Cassandra Web UI
    networks:
      - kinoprogramm-netzwerk

networks:
  kinoprogramm-netzwerk:
    driver: bridge

#volumes:
#  cassandra_data:
#    driver: local