version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: kinoprogramm-cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=KinoprogrammCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"   # CQL native transport port
      - "7000:7000"   # Inter-node cluster communication
      - "7001:7001"   # TLS inter-node cluster communication  
#      - "7199:7199"   # JMX monitoring port
#    volumes:
#      - cassandra_data:/var/lib/cassandra
#      - ./cassandra-init:/docker-entrypoint-initdb.d
    networks:
      - kinoprogramm-netzwerk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: kinoprogramm-cassandra-web
    environment:
      - CASSANDRA_HOST_IPS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=
      - CASSANDRA_PASSWORD=
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "3000:8083" # Cassandra Web UI
    networks:
      - kinoprogramm-netzwerk

networks:
  kinoprogramm-netzwerk:
    driver: bridge

#volumes:
#  cassandra_data:
#    driver: local